# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!

target 'SeventreesUser' do
  
pod 'YYKit', '~> 1.0.9'
  
pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'

pod 'AFNetworking', '~> 3.2.1'

pod 'SDWebImage', '~> 5.1.0'

pod 'Masonry', '~> 1.1.0'

pod 'MJExtension', '~> 3.1.0'

pod 'MJRefresh', '~> 3.2.0'

pod 'IQKeyboardManager', '~> 6.4.0'

pod 'SVProgressHUD', '~> 2.2.5'

pod 'SDCycleScrollView', '~> 1.80'

end
